logging:
  level:
    root: INFO
openai:
  token: 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
  temperature: 0.6
  presence_penalty: 0
  frequency_penalty: 0
  n: 1
  max_tokens: 500
  stop: null
  stream: false
  timeout: 100
  system_default: 你的名字叫小C，你回答内容请尽可能的精准简洁。
  welcome_words: 你的名字叫小C，现在用户首次使用小C。请你用优美的语句来欢迎他并给出与小C相对应的聊天技巧。
wxchat:
  frequency_response: 小C正在处理您上个问题。为了保证会话连贯，请耐心等待!
  default_welcome_words_end: -->(我现在处于测试阶段，有任何问题或者好的建议可以联系客服微信：AIXC2023)
  chatMaxCatch: 4
wx:
  mp:
    app-id: wxba4cf742c969fb56
    secret: a5477d800eb2501068840fed99dafda1
    token: axovhm2nIJZDRPzx2ZcQ9bnsZd
    aes-key: axovhm2nIJZDRPzx2ZcQ9bnsZdraKa37jFr81Dc9Xhc
    #    #单机和sentinel同时存在时，优先使用sentinel配置
    #    #wx.mp.config-storage.redis.sentinel-ips=127.0.0.1:16379,127.0.0.1:26379
    #    #wx.mp.config-storage.redis.sentinel-name=mymaster
    #    # http客户端配置
    #    wx.mp.config-storage.http-client-type=httpclient      # http客户端类型: HttpClient(默认), OkHttp, JoddHttp
    #    wx.mp.config-storage.http-proxy-host=
    #    wx.mp.config-storage.http-proxy-port=
    #    wx.mp.config-storage.http-proxy-username=
    #    wx.mp.config-storage.http-proxy-password=
    #    # 公众号地址host配置
    #    #wx.mp.hosts.api-host=http://proxy.com/
    #    #wx.mp.hosts.open-host=http://proxy.com/
    #    #wx.mp.hosts.mp-host=http://proxy.com/
redislock:
  expireSeconds: 60
  chatTimeOut: 600
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
  aop:
    auto: true
server:
  port: 80