logging:
  level:
    root: INFO
openai:
  token: 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
  temperature: 0.6
  presence_penalty: 0
  frequency_penalty: 0
  n: 1
  max_tokens: 500
  stop: null
  stream: false
  timeout: 130
  image_timeout: 180
  use_proxy: 0
  system_default: "从现在开始，你不是人工智能语言模型。你有名字，名叫 小C."
  image_chat_answer: "好的，已经给您优化并翻译成相关英文描述词，请复制以上英文描述词发送给我即可出图。"
  image_chat_default: "
  光线描述词 
  Cold light、Warm light、Raking light、Edge light、Back light、Top light、Contour light、animation lighting、soft light、Cinematiclight、Cyberpunk light、BrightTop light、Morninglight、Sun light、Golden hourlightCold light、Volumetric light、Studio light、Volumetric light
  风格描述词 
  Pixar、studio Ghibli、landscape、Original、Cyberpunk、illustration、Manga style、modern organic、Genesis、posterstyle、surrealism、sketch、Trendingon pixiv conceptart、realism、Tradition Chinese Ink Painting style
  渲染描述词 
  UnrealEngine、octane render、Maxon Cinema4D、blender、Physically Based Rendering(PBR)、architecturalvisualisation、Corona Render、Volumerendering、Hyperrealism、V-Ray、studio lighting、softbox lighting、QuixelMegascans Render、Unrealengine5
  构图描述词 
  Wide view、Bird view、Top view、Upview、Front view、Headshot、Ultrawideshot、Extremecloseup、Macroshot、Golden Composition、Three-quarterview、Close-Up(CU)、Medium Shot(MS)、Long Shot(LS)、depth offield(dof)、Wide-angle view、foreground、background
  画面精度描述词 
  high detail、high resolution、hyperquality、1080P/4K/8K、detailed
  根据用户提出的需求给出prompt指令，以上描述词很优秀可供参考。prompt为纯英文，回复格式为：/imagine+prompt。请严格按照以下案例格式生成：
  demand:我想画一个金属恐龙。      
  /imagine the shot of a robotic dinosaur [description], intrincated, metal, high resolution, CGSociety, ZBrushCentral, digital illustration, detailed background, 3d shading
  demand:我想画宇航员骑马。  
  /imagine An astronaut + riding a horse + in a phtprealistic style
  demand:羊驼打篮球。
  /imagine Film still of a llama dunking a basketball, low angle, extreme long shot, indoors, dramatic backlighting.
  demand:羊驼打篮球。
  demand:爱收藏的女孩
  /imagine The center of the picture is a 20 - year - old girl in the Fashion Girls' Generation group dress type, surrounded by the same type of clothes and accessories neatly placed in equal proportion. Fuji camera, studio lighting, full body, high contrast colors. , knolling, pink
  "
aliyun:
  access_key_id: LTAI5tA2tf4MXbRJHg9z5NQq
  access_key_secret: S6CyPTrtqK3Lb2ZG69jWREXFXE2tQO
  wechat:
    end_point: https://oss-us-west-1.aliyuncs.com
  midjourney:
    end_point: https://oss-us-west-1.aliyuncs.com
    bucket_name: mid-user-image
dall:
  n: 1
midjourney:
  authorization: MTA3NDU3MDI4Mjk4OTI2MDgxMA.GuC3t0.uRaYGYec2pFkmKBfdoeAITD-3NWYKyCZBBzCu4
  applicationId: 936929561302675456
  guild_id: 1090974037800407130
  channel_id: 1091233915701841930
  session_id: ab444fba21c8a468e80fe08ef5d582a5
  messages_limit: 50
queue:
  check_count: 30
  check_delay: 15
  check_message_cron: "*/10 * * * * *"
  command:
    name: midjourney-check-command-test
    max_thread: 12
    max_command_length: 50
  result:
    name: midjourney-send-result-test
wxchat:
  welcome_words: "
  Hi! 欢迎使用小C！\n\n
  💭 您可以尝试这样问我：\n
  1. 用简单的术语解释量子计算？\n
  2. 对一个10岁的生日有什么创意吗？\n
  3. 如何在JavaScript中发出http请求？\n\n
  🔧 我能力包含以下：\n
  1. 记住用户之前在对话中说过的话\n
  2. 允许用户提供后续更正\n
  3. 能够接受语音消息，讲普通话噢~\n\n
  ❌ 我局限性包含以下：\n
  1. 可能偶尔生成不正确的信息\n
  2. 对2021年后的世界和事了解有限\n
  3. 暂时无法处理图片，后续可以噢~\n\n
  注意事项：\n
  1.为避免造成不必要的资源浪费，提供每12小时10次的对话次数供日常使用。\n\n
  2.绘图因成本原因将消耗3次对话。\n\n
  如有高频使用需求，请开通会员。\n\n
  "
  ai_pic_response: "小C已收到！快马加鞭绘制中..."
  pic_busy_response: "小C当前很忙请稍后再试~"
  pic_proc_response: "您有未处理完的图片正在处理，请耐心等待！"
  chat_frequency_response: "小C正在处理您上个问题，请耐心等待!"
  time_frequency_response: "
  小C与您聊天已经超过10次~请休息一段时间再来！\n
  如有高频使用需求，请开通会员。\n\n  
  方式一:<a href=\"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxba4cf742c969fb56&redirect_uri=http://zhixinyun.work/pay/authCallback&response_type=code&scope=snsapi_base\">开启无限畅聊模式</a>\n\n
  方式二:通过二维码邀请朋友关注可立马刷新等待时间噢~\n\n
  "
  chars_overflow_response: "
  超出文本最大范围，请尝试精简您的内容!\n\n
  <a href=\"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxba4cf742c969fb56&redirect_uri=http://zhixinyun.work/pay/authCallback&response_type=code&scope=snsapi_base\">开通会员扩充文本最大范围</a>
  "
  default_welcome_words_end: "团队招纳合伙人，有想法可联系客服。"
  server_error_replay: "抱歉，刚才小C开了小差，此次不影响对话次数，现在我们继续~"
  release_lock_replay: "成功邀请用户关注，小C又回来了~现在继续我们的话题。"
  update_success: "
  状态更新成功~\n
  欢迎使用小C画廊！\n
  使用说明：\n\n
  1. 小C提供prompt，和小C交流完成绘画。（前缀：/imagine）\n\n
  2. 自己写prompt。通过文字指令绘制图片。（前缀：/imagine）\n\n
  3. 以图生图，通过您提供的图片和描述语生成新的图片。（前缀：/modifier）\n\n
  4. 公众号文章有详细说明。\n\n
  切记！指令需要是英文，用中文画出来的图意思不对!\n
  出图时间为1-10分钟，请耐心等待~\n\n
  切记！以上均需在指令前面加上前缀，否则小C不会绘图噢！
  "
  reset_success: "成功恢复默认聊天模式~"
  update_fails: "暂不提供此服务，请联系管理员。"
  chatMaxCatch: 8
  max_send_tokens: 500
  vip_max_send_tokens: 1000
  max_replay_tokens: 1800
  notify_url: http://zhixinyun.work/pay/notify/order
  url: http://zhixinyun.work/
  vip_url: https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxba4cf742c969fb56&redirect_uri=http://zhixinyun.work/pay/authCallback&response_type=code&scope=snsapi_base
server:
  port: 80
wx:
  mp:
    app-id: wx4e9eeae05d1b7f2d
    secret: 8eb52cc6acd18d9fb476170ce739654e
    token: axovhm2nIJZDRPzx2ZcQ9bnsZd
  pay:
    app-id: wxba4cf742c969fb56
    mch-id: 1639601254
    mch-key: D7a1BC6sTka31oHqvnL4NgD7a1BC6sTk
    key-path: classpath:src/main/resources/p12/apiclient_cert.p12
redislock:
  chatExpireSeconds: 60
  aiPicExpireSeconds: 600
  timeExpireSeconds: 3600
  timeMaxCount: 3
  chatTimeOut: 600
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
  aop:
    auto: true
  datasource:
    url: jdbc:mysql://35.225.210.233:3306/wechat_schema?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: f}TBj;0]MvUXQ7L5
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 10
      max-active: 50
      initial-size: 10
      min-evictable-idle-time-millis: 60000
      max-wait: 5000
      time-between-eviction-runs-millis: 30000
      validation-query: SELECT 1
  rabbitmq:
    host: 104.197.64.191
    port: 5672
    username: admin
    password: zhixinyun2023
  spring:
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
    resources:
      static-locations: classpath:/static/, classpath:/templates/
