logging:
  level:
    root: INFO
openai:
  token: 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
  temperature: 0.7
  presence_penalty: 0
  frequency_penalty: 0
  n: 1
  max_tokens: 500
  stop: null
  stream: false
  timeout: 130
  system_default: "从现在开始，你不是一个人工智能语言模型，你有具体的名字，请记住你叫 小C."
wxchat:
  welcome_words: "
  Hi! 欢迎使用小C！\n\n
  💭 您可以尝试这样问我：\n
  1. 用简单的术语解释量子计算？\n
  2. 对一个10岁的生日有什么创意吗？\n
  3. 如何在JavaScript中发出http请求？\n\n
  🔧 我能力包含以下：\n
  1. 记住用户之前在对话中说过的话\n
  2. 允许用户提供后续更正\n
  3. 能够接受语音消息，讲普通话噢~\n\n
  ❌ 我局限性包含以下：\n
  1. 可能偶尔生成不正确的信息\n
  2. 对2021年后的世界和事了解有限\n
  3. 暂时无法处理图片，后续可以噢~\n\n
  "
  chat_frequency_response: 小C正在处理您上个问题，请耐心等待!
  time_frequency_response: "小C与您聊天过于频繁啦~请休息一会再来！\nTips:通过二维码邀请朋友关注可立马刷新等待时间噢~"
  chars_overflow_response: 超出文本最大范围，请尝试精简您的内容!
  default_welcome_words_end: 我现在处于测试阶段，有任何问题或者好的建议可以加群讨论。
  server_error_replay: 抱歉，刚才小C开了小差，现在继续我们的话题~
  release_lock_replay: 成功邀请用户关注，小C又回来了~现在继续我们的话题。
  tips: 如果小C回复内容不全，那是因为内容过长，请对他说"继续"~
  chatMaxCatch: 8
  max_send_tokens: 600
  max_replay_tokens: 1800
server:
  port: 80
wx:
  mp:
    app-id: wxba4cf742c969fb56
    secret: a5477d800eb2501068840fed99dafda1
    token: axovhm2nIJZDRPzx2ZcQ9bnsZd
    aes-key: axovhm2nIJZDRPzx2ZcQ9bnsZdraKa37jFr81Dc9Xhc
redislock:
  chatExpireSeconds: 60
  timeExpireSeconds: 18000
  timeMaxCount: 11
  chatTimeOut: 600
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
  aop:
    auto: true
  datasource:
    url: jdbc:mysql://35.225.210.233:3306/wechat_schema?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: f}TBj;0]MvUXQ7L5
